---
# Script to change value of an entry into sellyoursaas.conf
#
# To run the script:
# ansible-playbook change_sellyoursaas_config.yml --extra-vars='option=<your_option> value=<new_value>'
#

- name: Change value in conf
  hosts: deployment
  become: yes
  remote_user: gkervern

  tasks:
  - name: Change conf value
    ini_file:
      path: /etc/sellyoursaas.conf
      section: null
      option: "{{ option }}"
      value: "{{ value }}"
      no_extra_spaces: yes
      backup: yes
