---
# Script to change password of a user on a set of servers
#
# To run the script:
# ansible-playbook change_password.yml --extra-vars='my_remote_user=<your_remote_user> user_to_update=<login_of_user> password=<new_password>'
# To run the script for servers into targethost section of hosts-xxx file:
# ansible-playbook -i hosts-xxx change_password.yml -e 'target=targethost my_remote_user=<your_remote_user> user_to_update=<login_of_user> password=<new_password>'
#

- name: Playbook to change password on servers for a user
  hosts: '{{target}}'
  become: yes
  remote_user: "{{ my_remote_user }}"

  tasks:
  - name: Change password
    user:
      user: "{{ user_to_update }}"
      password: "{{ password |password_hash('sha512', 'mysalt') }}"
