---
#launch with --extra-vars='my_remote_user=<your_remote_user> user_to_update=<login_of_user> password=<new_password>'
- name: Playbook to change password on all servers for a user
  hosts: all
  become: yes
  remote_user: "{{ my_remote_user }}"

  tasks:
  - name: Change password
    user:
      user: "{{ user_to_update }}"
      password: "{{ password |password_hash('sha512', 'mysalt') }}"
