---
- name: Update SellYourSaas on servers
  hosts: deployment
  user: gkervern
  become: yes
  become_method: sudo
  become_user: admin
  tasks:
  - name: Launch git_update_sellyoursaas.sh
    command: /home/admin/wwwroot/dolibarr_sellyoursaas/scripts/git_update_sellyoursaas.sh /home/admin/wwwot/
