---
# Script to run clean.sh command on servers
#
# To run the script:
# ansible-playbook launch_clean.yml --extra-vars='target=targethost command=(test|confirm)'
#

- name: Cleanup servers
  hosts: '{{target}}'
  user: gkervern
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: Launch clean.sh
    command: "/home/admin/wwwroot/dolibarr_sellyoursaas/scripts/clean.sh {{ command }}"
