---
# Script to run git_update_sellyoursaas.sh to update SellYourSaas on servers
#
# To run the script:
# ansible-playbook launch_git_update_sellyoursaas.yml -i hosts-xxx -e 'target=targethost'
# ansible-playbook launch_git_update_sellyoursaas.yml -i hosts-xxx -e 'target=targethost' --limit=*.mydomain.com

- name: Update SellYourSaas on servers
  hosts: '{{target}}'
  user: gkervern
  become: yes
  become_method: sudo
  become_user: admin
  tasks:
  - name: Launch git_update_sellyoursaas.sh
    command: /home/admin/wwwroot/dolibarr_sellyoursaas/scripts/git_update_sellyoursaas.sh /home/admin/wwwot/
